import { test, expect } from '@playwright/test';
import { isolatedContext, OWNER_STATE } from './helpers';

test.describe('Settings (live)', () => {
  test('updates the gym profile and it persists', async ({ browser }) => {
    const { context, page } = await isolatedContext(browser, { storageState: OWNER_STATE });
    try {
      const addr = `E2E Tower ${Date.now().toString().slice(-5)}, Road No. 36`;
      await page.goto('/settings');
      await expect(page.getByText('GymTech Fitness Club').first()).toBeVisible({ timeout: 30000 });
      // Wait for the profile query to seed the form before typing.
      await expect(page.getByPlaceholder(/phoenix prime tower/i)).not.toHaveValue('', { timeout: 30000 });
      await page.getByPlaceholder(/phoenix prime tower/i).fill(addr);
      await page.getByRole('button', { name: /save profile changes/i }).click();
      await expect(page.getByText(/profile updated|saved|success/i).first()).toBeVisible({ timeout: 30000 });
      await page.reload();
      await expect(page.getByPlaceholder(/phoenix prime tower/i)).toHaveValue(addr, { timeout: 30000 });
    } finally {
      await context.close();
    }
  });

  test('saves notification triggers', async ({ browser }) => {
    const { context, page } = await isolatedContext(browser, { storageState: OWNER_STATE });
    try {
      await page.goto('/settings/notifications');
      await expect(page.getByText(/welcome message/i).first()).toBeVisible({ timeout: 30000 });
      await page.getByRole('button', { name: /save notification triggers/i }).click();
      await expect(page.getByText(/saved|success|updated/i).first()).toBeVisible({ timeout: 30000 });
    } finally {
      await context.close();
    }
  });
});

test.describe('Reports (live)', () => {
  test('all tabs render real data and CSV export downloads', async ({ browser }) => {
    const { context, page } = await isolatedContext(browser, { storageState: OWNER_STATE });
    try {
      await page.goto('/reports');
      await expect(page.getByText('Period Revenue').first()).toBeVisible({ timeout: 45000 });

      for (const tab of ['Revenue', 'Membership', 'Attendance', 'Growth']) {
        await page.getByRole('tab', { name: new RegExp(`^${tab}`) }).click();
        await expect(page.locator('main')).not.toContainText('Something went wrong', { timeout: 30000 });
      }

      // Back to overview for the export panel.
      await page.getByRole('tab', { name: /^overview/i }).click();
      await page.keyboard.press('Escape');
      await expect(page.getByText('Data Exports')).toBeVisible({ timeout: 30000 });
      const downloadPromise = page.waitForEvent('download', { timeout: 30000 });
      await page.getByRole('button', { name: /members directory/i }).click();
      const download = await downloadPromise;
      const path = await download.path();
      if (!path) throw new Error('CSV download produced no file');
    } finally {
      await context.close();
    }
  });
});

test.describe('Audit logs (live)', () => {
  test('shows the actions performed during this run and filters them', async ({ browser }) => {
    const { context, page } = await isolatedContext(browser, { storageState: OWNER_STATE });
    try {
      await page.goto('/audit-logs');
      await expect(page.getByText(/activity stream/i)).toBeVisible({ timeout: 30000 });
      // Actions generated by the E2E run itself must be recorded.
      await expect(page.getByText(/member\.create|payment\.create/i).first()).toBeVisible({ timeout: 30000 });
      await page.getByPlaceholder(/filter by action/i).fill('payment.create');
      await expect(page.getByText('payment.create').first()).toBeVisible({ timeout: 30000 });
    } finally {
      await context.close();
    }
  });
});
